hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold : 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 60